import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  statusBarPlaceholder: {
    height: 40,
    backgroundColor: '#ffffff',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 24,
  },
  card: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
  },
  header: {
    marginBottom: 40,
    alignItems: 'center',
  },
  logoIcon: {
    width: 72,
    height: 72,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#000',
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  brand: {
    fontSize: 10.4,
    fontWeight: '800',
    letterSpacing: 6.4,
    textTransform: 'uppercase',
    color: '#a3a3a3',
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: '300',
    letterSpacing: -0.56,
    color: '#000',
  },
  form: {
    width: '100%',
    gap: 20,
  },
  field: {
    textAlign: 'left',
    width: '100%',
  },
  label: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 2.4,
    color: '#a3a3a3',
    marginLeft: 4,
    marginBottom: 6.4,
  },
  input: {
    width: '100%',
    paddingVertical: 14.4,
    paddingHorizontal: 19.2,
    backgroundColor: '#f9f9f9',
    borderWidth: 1,
    borderColor: '#f0f0f0',
    borderRadius: 12,
    fontSize: 14.4,
    color: '#000',
  },
  inputFocused: {
    backgroundColor: '#fff',
    borderColor: '#000',
  },
  formRow: {
    flexDirection: 'row',
    gap: 16,
  },
  formRowMobile: {
    flexDirection: 'column',
  },
  passwordContainer: {
    position: 'relative',
    width: '100%',
  },
  inputPassword: {
    width: '100%',
    paddingVertical: 14.4,
    paddingHorizontal: 19.2,
    paddingRight: 50,
    backgroundColor: '#f9f9f9',
    borderWidth: 1,
    borderColor: '#f0f0f0',
    borderRadius: 12,
    fontSize: 14.4,
    color: '#000',
  },
  eyeIcon: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
  },
  eyeText: {
    fontSize: 20,
    color: '#666',
  },
  button: {
    width: '100%',
    height: 56,
    backgroundColor: '#000',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14.4,
    borderRadius: 12,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  buttonDisabled: {
    opacity: 0.3,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14.4,
  },
  inputError: {
    borderColor: '#ff4444',
  },
  fieldError: {
    fontSize: 10,
    color: '#ff4444',
    marginTop: 4,
    marginLeft: 4,
  },
  fieldSuccess: {
    fontSize: 10,
    color: '#22c55e',
    marginTop: 4,
    marginLeft: 4,
  },
  requirementsContainer: {
    marginTop: 8,
    gap: 4,
  },
  requirement: {
    fontSize: 10,
    color: '#999',
    marginLeft: 4,
  },
  requirementMet: {
    color: '#22c55e',
  },
  successState: {
    paddingVertical: 40,
    paddingHorizontal: 40,
    backgroundColor: '#f9f9f9',
    borderRadius: 24,
  },
  successIcon: {
    width: 56,
    height: 56,
    backgroundColor: '#000',
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    alignSelf: 'center',
  },
  iconCheck: {
    width: 24,
    height: 24,
    color: '#fff',
  },
  successTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 8,
  },
  successText: {
    fontSize: 13,
    color: '#a3a3a3',
    textAlign: 'center',
  },
  errorMessage: {
    paddingVertical: 12.8,
    paddingHorizontal: 12.8,
    backgroundColor: '#000',
    color: '#fff',
    borderRadius: 12,
    fontSize: 11.2,
  },
  footer: {
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#f5f5f5',
    fontSize: 12,
    color: '#a3a3a3',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: '#a3a3a3',
  },
  link: {
    color: '#000',
    fontWeight: 'bold',
    marginLeft: 4,
  },
});

export default styles;
