import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 200,
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  drawer: {
    position: 'relative',
    width: '100%',
    maxWidth: 400,
    height: '100%',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: -20, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 50,
    elevation: 10,
    flexDirection: 'column',
  },
  header: {
    paddingVertical: 40,
    paddingHorizontal: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  headerLeft: {
    flex: 1,
  },
  badge: {
    fontSize: 8,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 3.2,
    color: '#a3a3a3',
    marginBottom: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: '300',
    margin: 0,
    color: '#000',
  },
  btnClose: {
    backgroundColor: '#f9f9f9',
    borderWidth: 0,
    padding: 9.6,
    borderRadius: 50,
  },
  closeIcon: {
    width: 20,
    height: 20,
  },
  content: {
    flex: 1,
    padding: 32,
    gap: 24,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#fafafa',
  },
  dateBox: {
    backgroundColor: '#000',
    color: '#fff',
    width: 50,
    height: 55,
    borderRadius: 12,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  day: {
    fontSize: 17.6,
    fontWeight: '800',
    color: '#fff',
  },
  month: {
    fontSize: 9.6,
    textTransform: 'uppercase',
    fontWeight: '600',
    opacity: 0.7,
    color: '#fff',
  },
  info: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 14.4,
    fontWeight: '700',
    margin: 0,
    marginBottom: 4,
    color: '#000',
  },
  eventDate: {
    fontSize: 12,
    color: '#666',
    marginBottom: 3.2,
  },
  eventLocation: {
    fontSize: 12,
    color: '#a3a3a3',
    margin: 0,
  },
  eventDetails: {
    fontSize: 12,
    color: '#a3a3a3',
    margin: 0,
  },
  chevron: {
    fontSize: 24,
    color: '#d4d4d4',
    fontWeight: '300',
    marginLeft: 8,
  },
  empty: {
    textAlign: 'center',
    color: '#d4d4d4',
    marginTop: 64,
    fontSize: 13.6,
  },
});

export default styles;